[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
